### ISSUE TITLE
Issues on configuration connector exchange

### ISSUE THREAD

**Issue by audreypapin** [camptocamp/connector-exchange#12]
I have a new incident, I'm sorry.
I have this error that I can not understand:

```
`2018-07-31 07:40:23,609 5202 DEBUG OPTIMAV10 odoo.addons.connector_exchange.models.exchange_backend.common: export calendar events
2018-07-31 07:40:23,633 5202 DEBUG OPTIMAV10 root: Request: 
<soap:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <soap:Header>


            <t:RequestServerVersion Version="Exchange2010_SP2"/>


            <t:ExchangeImpersonation>


                    <t:ConnectingSID>


                            <t:PrincipalName>audrey.papin@optimadsi.fr</t:PrincipalName>


                    </t:ConnectingSID>


            </t:ExchangeImpersonation>


    </soap:Header>


    <soap:Body>



            <m:GetUserConfiguration>


                    <m:UserConfigurationName Name="CategoryList">


                            <t:DistinguishedFolderId Id="calendar"/>


                    </m:UserConfigurationName>


                    <m:UserConfigurationProperties>All</m:UserConfigurationProperties>


            </m:GetUserConfiguration>



    </soap:Body>
</soap:Envelope>

2018-07-31 07:40:23,634 5202 INFO OPTIMAV10 requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): mel.optimadsi.fr
2018-07-31 07:40:23,747 5202 DEBUG OPTIMAV10 requests.packages.urllib3.connectionpool: "POST /autodiscover/services.wsdl HTTP/1.1" 405 112
2018-07-31 07:40:23,748 5202 ERROR OPTIMAV10 odoo.addons.base.ir.ir_cron: Call of self.env[u'exchange.backend'].cron_export_calendar(*()) failed in Job 18
Traceback (most recent call last):
File "/odoo/odoo-server/odoo/addons/base/ir/ir_cron.py", line 119, in _callback
getattr(model, method_name)(*args)
File "/odoo/custom/addons/connector_exchange/models/exchange_backend/common.py", line 151, in cron_export_calendar
backend.export_user_calendar()
File "/odoo/custom/addons/connector_exchange/models/exchange_backend/common.py", line 247, in export_user_calendar
user.create_odoo_category()
File "/odoo/custom/addons/connector_exchange/models/res_users/res_users.py", line 105, in create_odoo_category
ews.UpdateCategoryList('Odoo', 23, WellKnownFolderName.Calendar)
File "/usr/local/lib/python2.7/dist-packages/pyews/pyews.py", line 149, in UpdateCategoryList
"All")
File "/usr/local/lib/python2.7/dist-packages/pyews/pyews.py", line 132, in GetUserConfiguration
resp = req.execute()
File "/usr/local/lib/python2.7/dist-packages/pyews/ews/request_response.py", line 307, in execute
self.resp_node = self.request_server(debug=True)
File "/usr/local/lib/python2.7/dist-packages/pyews/ews/request_response.py", line 69, in request_server
return self.ews.send(r, debug)
File "/usr/local/lib/python2.7/dist-packages/pyews/pyews.py", line 650, in send
return self.soap.send(req, debug)
File "/usr/local/lib/python2.7/dist-packages/pyews/soap.py", line 104, in send
logging.debug('%s', pretty_xml(r.text.encode('utf-8')))
File "/usr/local/lib/python2.7/dist-packages/pyews/utils.py", line 46, in pretty_xml
x = xml.dom.minidom.parseString(x).toprettyxml()
File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
return expatbuilder.parseString(string)
File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
return builder.parseString(string)
File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
parser.Parse(string, True)
ExpatError: syntax error: line 1, column 0
```
`

Any ideas ?
Thanks for your help

**Comment by audreypapin** [comment]
it seems to be the return format of the file that is not good. I'm stuck really stuck

**Comment by audreypapin** [comment]
```
Traceback (most recent call last):
  File "/odoo/custom/addons/queue_job/controllers/main.py", line 104, in runjob
    self._try_perform_job(env, job)
  File "/odoo/custom/addons/queue_job/controllers/main.py", line 62, in _try_perform_job
    job.perform()
  File "/odoo/custom/addons/queue_job/job.py", line 369, in perform
    self.result = self.func(*tuple(self.args), **self.kwargs)
  File "/odoo/custom/addons/connector_exchange/connector.py", line 99, in export_record
    return exporter.run(self, fields=fields)
  File "/odoo/custom/addons/connector_exchange/unit/exporter.py", line 53, in run
    result = self._run(*args, **kwargs)
  File "/odoo/custom/addons/connector_exchange/models/calendar_event/exporter.py", line 436, in _run
    self.create_exchange_calendar_event(fields)
  File "/odoo/custom/addons/connector_exchange/models/calendar_event/exporter.py", line 405, in create_exchange_calendar_event
    record, folder = self._create_data(fields=fields)
  File "/odoo/custom/addons/connector_exchange/models/calendar_event/exporter.py", line 351, in _create_data
    self.binding.calendar_folder
  File "/odoo/custom/addons/connector_exchange/models/calendar_event/exporter.py", line 331, in check_folder_still_exists
    folder = adapter.find_folder(odoo_folder)
  File "/odoo/custom/addons/connector_exchange/models/calendar_event/adapter.py", line 38, in find_folder
    self.ews.get_root_folder()
  File "/usr/local/lib/python2.7/dist-packages/pyews/pyews.py", line 663, in get_root_folder
    WellKnownFolderName.MsgFolderRoot)
  File "/usr/local/lib/python2.7/dist-packages/pyews/ews/folder.py", line 111, in bind
    resp = req.execute()
  File "/usr/local/lib/python2.7/dist-packages/pyews/ews/request_response.py", line 206, in execute
    self.resp_node = self.request_server(debug=True)
  File "/usr/local/lib/python2.7/dist-packages/pyews/ews/request_response.py", line 69, in request_server
    return self.ews.send(r, debug)
  File "/usr/local/lib/python2.7/dist-packages/pyews/pyews.py", line 650, in send
    return self.soap.send(req, debug)
  File "/usr/local/lib/python2.7/dist-packages/pyews/soap.py", line 104, in send
    logging.debug('%s', pretty_xml(r.text.encode('utf-8')))
  File "/usr/local/lib/python2.7/dist-packages/pyews/utils.py", line 46, in pretty_xml
    x = xml.dom.minidom.parseString(x).toprettyxml()
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: no element found: line 1, column 0
```

**Comment by audreypapin** [comment]
Nobody for help ?

**Comment by audreypapin** [comment]
pleaseeeeeeee
